package:
  name: channelfinder
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0') }}


source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - pip
    - python =3.8
  run:
    - python =3.8
    - requests >=2.15.0
    - simplejson >=3.10.0
    - urllib3 >=1.22


test:
  imports:
    - channelfinder

about:
  home: https://github.com/AdvancedPhotonSource/pyCFClient.git
  summary: Channelfinder client for python.

