package:
  name: py_cf_client
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0') }}


source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python >=3.6
  run:
    - python >=3.6
    - requests =2.23.0
    - urllib3 >=1.22

test:
  imports:
    - channelfinder

about:
  home: https://git.aps.anl.gov/C2/conda/c2-tool
  summary: Installs python client for Channelfinder server.

